CEGIS_Project_ProgressApp/Controllers/ProjectInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.WebPages;
using CEGIS_Project_ProgressApp.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace CEGIS_Project_ProgressApp.Controllers
{
    public class ProjectInfoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProjectInfoes
        public ActionResult Index()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            string initial = User.Identity.Name;
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Initial == initial);
            int userType = currentUser.UserType;
            int divisionId = currentUser.DivisionId;
            string email = currentUser.Email;



            var projectInfos = db.ProjectInfos.Include(p => p.Division).Include(p => p.ExpectedDate).Include(p => p.ProgressType).Include(p => p.ProjectType);
            if (userType == 2)
            {
                try
                {
                    var filteredResult = projectInfos.Where(s => s.DivisionId == divisionId);
                    ViewBag.UserTypes = currentUser.UserType;
                    return View(filteredResult.ToList());

                }
                catch (Exception)
                {
                    
                }             
 
            }
            if (userType == 3)
            {
                ViewBag.UserTypes = currentUser.UserType;
                return View(projectInfos.ToList());
            }

            return View(projectInfos.ToList());
        }

        // GET: ProjectInfoes/Details/5

        //public JsonResult Details(int id)
        //{
        //    //var districtList = db.Districts.Where(a => a.Division_id == divisionId).ToList();
        //    //if (id == null)
        //    //{
        //    //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    //}
        //    var projectInfo = db.ProjectInfos.Where(p=>p.Id==id).ToList();

        //    //if (projectInfo == null)
        //    //{
        //    //    return HttpNotFound();
        //    //}
        //    //return View(projectInfo);
        //    return Json(projectInfo, JsonRequestBehavior.AllowGet);
        //}
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectInfo projectInfo = db.ProjectInfos.Find(id);
            if (projectInfo == null)
            {
                return HttpNotFound();
            }


           return PartialView(projectInfo); 


            //return View(projectInfo);
        }

        // GET: ProjectInfoes/Create
        public ActionResult Create()
        {

            string initial = User.Identity.Name;
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Initial == initial);
            ViewBag.UserTypes = currentUser.UserType;
            int dId = currentUser.DivisionId;
            ViewBag.DivId = currentUser.DivisionId;
            ViewBag.AllDivision = db.LookUpDivisions.Where(a => a.DivisionId == dId).ToList();

            //string email = currentUser.Email;
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            ViewBag.DivisionId = new SelectList(db.LookUpDivisions, "DivisionId", "DivFullName");
            ViewBag.ExpectedDateId = new SelectList(db.ExpectedDates, "Id", "Dates");
            ViewBag.ProgressTypeId = new SelectList(db.ProgressTypes, "Id", "Progress");
            ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "Id", "TypeName");


            return View();
        }

        // POST: ProjectInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DivisionId,ProjectName,Client,FocalPerson,ProgressTypeId,ContactValue,ProjectTypeId,Probility,Duration,ExpectedDateId,DateTimes,UserInitial")] ProjectInfo projectInfo)
        {
            string initial = User.Identity.Name;
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Initial == initial);
            string email = currentUser.Email;


            int dId = currentUser.DivisionId;
            var divName = db.LookUpDivisions.Find(dId);
            string DivisionName = divName.DivFullName;

            if (ModelState.IsValid)
            {
                db.ProjectInfos.Add(projectInfo);
                db.SaveChanges();

                //Data maping object to our database
                UpdateHistory aUpdateHistory = new UpdateHistory();
                aUpdateHistory.ProjectId = projectInfo.Id;
                aUpdateHistory.UpdatedBy = projectInfo.UserInitial+ " (Project Creator)";                
                aUpdateHistory.ProgressTypeId = projectInfo.ProgressTypeId;
                aUpdateHistory.UpdateTime = DateTime.Now;
                db.UpdateHistorys.Add(aUpdateHistory);
                db.SaveChanges();

                try
                {
                    //Configuring webMail class to send emails  
                    //gmail smtp server  
                    WebMail.SmtpServer = "smtp.gmail.com";
                    //gmail port to send emails  
                    WebMail.SmtpPort = 587;
                    WebMail.SmtpUseDefaultCredentials = true;
                    //sending emails with secure protocol  
                    WebMail.EnableSsl = true;
                    //EmailId used to send emails from application  
                    WebMail.UserName = "rimu.cse45@gmail.com";
                    WebMail.Password = "rimu1234";

                    //Sender email address.  
                    WebMail.From = email;
                    //$message_body = 'Dear User,' . "\r\n" . "\r\n" . 'Your organization '. $orgName . ' is not fullfilling the MRA criteria. This is a showcause letter to this organization'. " \r\n" . "\r\n" . 'Thanks' . "\r\n" . 'Microcredit Regulatory Authority';
                    //Send email  
                    //WebMail.Send(to: "moshiur.mgmh@gmail.com moshiur_cse@hotmail.com", subject: "New Project Added into Business Harnessing Monitoring Tools",
                    //             body: "Project Name: " + projectInfo.ProjectName +  "  \nAdded By: " + projectInfo.User + "\n Email: " + email,
                    //             cc: "", bcc: "", isBodyHtml: true);


                    WebMail.Send(to: "moshiur.mgmh@gmail.com sislam @cegisbd.com", subject: "New Project Added into Business Harnessing Monitoring Tools",
                                 body:  "<h1>Project Name: " + projectInfo.ProjectName + "</h1>" +
                                        "<p>Division Name: " + DivisionName + "</p>" +                                       
                                        "<p>Added By : " + projectInfo.UserInitial + "</p>" +
                                        "<p>Email : " + email + "</p>",
                                 cc: "", bcc: "", isBodyHtml: true);

                    //ViewBag.Status = "Email Sent Successfully.";
                    //sislam @cegisbd.com
                }
                catch (Exception)
                {
                    //ViewBag.Status = "Problem while sending email, Please check details.";

                }
                
                return RedirectToAction("Index");
            }

            ViewBag.DivisionId = new SelectList(db.LookUpDivisions, "DivisionId", "DivFullName", projectInfo.DivisionId);
            ViewBag.ExpectedDateId = new SelectList(db.ExpectedDates, "Id", "Dates", projectInfo.ExpectedDateId);
            ViewBag.ProgressTypeId = new SelectList(db.ProgressTypes, "Id", "Progress", projectInfo.ProgressTypeId);
            ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "Id", "TypeName", projectInfo.ProjectTypeId);

            
            return View(projectInfo);
        }

        // GET: ProjectInfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectInfo projectInfo = db.ProjectInfos.Find(id);
            if (projectInfo == null)
            {
                return HttpNotFound();
            }
            ViewBag.DivisionId = new SelectList(db.LookUpDivisions, "DivisionId", "DivFullName", projectInfo.DivisionId);
            ViewBag.ExpectedDateId = new SelectList(db.ExpectedDates, "Id", "Dates", projectInfo.ExpectedDateId);
            ViewBag.ProgressTypeId = new SelectList(db.ProgressTypes, "Id", "Progress", projectInfo.ProgressTypeId);
            ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "Id", "TypeName", projectInfo.ProjectTypeId);
            return PartialView(projectInfo);
            //return View(projectInfo);
        }

        // POST: ProjectInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

CEGIS_Project_ProgressApp/Views/ProjectInfoes/Create.cshtml
@using System.Security.Claims
@using CEGIS_Project_ProgressApp.Models
@model CEGIS_Project_ProgressApp.Models.ProjectInfo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create New Project</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (ViewBag.UserTypes == 2)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.DivisionId, "Division", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.DropDownList("DivisionId", null, htmlAttributes: new {@class = "form-control"})*@
                    @*@Html.DropDownList("DivisionId", (SelectList)ViewBag.DivId, htmlAttributes: new { @class = "form-control" })*@

                    <select id="DivisionId" name="DivisionId" class="form-control">
                        @foreach (LookUpDivision option in ViewBag.AllDivision)
                        {
                            <option value="@option.DivisionId" @(option.DivisionId == ViewBag.DivId ? "selected='selected'" : "")>@option.DivFullName</option>
                        }
                    </select>

                    @Html.ValidationMessageFor(model => model.DivisionId, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.DivisionId, "Division", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("DivisionId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DivisionId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Client, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Client, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Client, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FocalPerson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FocalPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FocalPerson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProgressTypeId, "Progress", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProgressTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProgressTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectTypeId, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Probility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Probility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Probility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpectedDateId, "Expected Date", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("ExpectedDateId", null, htmlAttributes: new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ExpectedDateId, "", new {@class = "text-danger"})
            </div>
        </div>
        @*<div class="form-group" style="display: none">
            @Html.LabelFor(model => model.Date, "Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @Value = @DateTime.Now } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group" style="display: none">
            @Html.LabelFor(model => model.UserInitial, "UserInitial", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.UserInitial, new { htmlAttributes = new { @class = "form-control", @Value = @User.Identity.Name } })
                @Html.ValidationMessageFor(model => model.UserInitial, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
                @Html.LabelFor(model => model.DateTimes, "DateTimes", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateTimes, new { htmlAttributes = new { @class = "form-control", @Value = @DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss") } })
                    @Html.ValidationMessageFor(model => model.DateTimes, "", new { @class = "text-danger" })
                </div>
         </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

CEGIS_Project_ProgressApp/Views/ProjectInfoes/Delete.cshtml
@model CEGIS_Project_ProgressApp.Models.ProjectInfo


<div class="row">
    <div class="col-md-12">
        <div class="modal-header" style="background-color: #254377">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 style="color: red; text-align: center">Are you sure you want to delete this?</h4>
        </div>
        <div class="modal-body">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Division.DivShortName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Division.DivFullName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ProjectName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ProjectName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Client)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Client)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.FocalPerson)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FocalPerson)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ProgressType.Progress)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ProgressType.Progress)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ContactValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ContactValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ProjectType.TypeName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ProjectType.TypeName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Probility)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Probility)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Duration)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Duration)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ExpectedDate.Dates)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ExpectedDate.Dates)
                </dd>

            </dl>
        </div>
        <div class="modal-footer" style="background-color: #2f4f4f">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color" style="float: right;" >
                    <input type="submit" id="id" value="Delete" class="btn btn-default" />
                    @*@Html.ActionLink("Back to List", "Index")*@
                </div>
            }
        </div>
    </div>
</div>

CEGIS_Project_ProgressApp/Views/ProjectInfoes/Index.cshtml
@model IEnumerable<CEGIS_Project_ProgressApp.Models.ProjectInfo>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section style
{
    <link href="~/Content/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-dialog.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/buttons.dataTables.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/buttons.jqueryui.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.jqueryui.css" rel="stylesheet" />
}

<h3>
    @Html.ActionLink("Add New Project", "Create")
</h3>
<table class="display" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Division.DivShortName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectName)
            </th> 
            <th>
                @Html.DisplayNameFor(model => model.Client)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FocalPerson)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProgressType.Progress)
            </th>
            @if (ViewBag.UserTypes != 3)
            {
                <th>
                    @Html.DisplayNameFor(model => model.ContactValue)
                </th>
            }
            <th>
                @Html.DisplayNameFor(model => model.ProjectType.TypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Probility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedDate.Dates)
            </th>
            <th><label>Action</label></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr id="show_@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Division.DivFullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FocalPerson)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProgressType.Progress)
                </td>
                @if (ViewBag.UserTypes != 3)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactValue)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectType.TypeName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Probility)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpectedDate.Dates)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { onclick = "edit_function(item.Id)" })*@

                    <a href="javascript:void(0);" class="anchorEdit" data-id="@item.Id">Edit |</a>

                    @*<input type="button" value="edit" class="btn_edit1 btn btn-default" id="@item.Id" />*@

                    @*@Html.ActionLink("Details", "Details", new {id = item.Id})*@

                    <a href="javascript:void(0);" class="anchorDetail" data-id="@item.Id">Details |</a>

                    @if (ViewBag.UserTypes != 2)
                    {
                        //@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { onclick = "return confirm('Are You Sure to Delete?')" })

                        <a href="javascript:void(0);" class="anchorDelete" data-id="@item.Id">Delete</a>
                    }
                </td>
            </tr>
            @*</tbody>
                        </table>
                    </td>
                </tr>*@
        }
    </tbody>
</table>

@section scripts
{
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/bootstrap-dialog.js"></script>

    <script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.flash.min.js"></script>

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.jqueryui.js"></script>

    <script src="~/Scripts/DataTables/buttons.jqueryui.min.js"></script>
    <script src="~/Scripts/DataTables/pdfmake.min.js"></script>

    <script src="~/Scripts/DataTables/jszip.min.js"></script>
    <script src="~/Scripts/DataTables/vfs_fonts.js"></script>
    <script src="~/Scripts/DataTables/buttons.html5.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.print.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.colVis.js"></script>

    <script>
        $(function (){

            $('#myTable').DataTable({
                dom: 'Bfrtip',
                lengthChange: false,
                //buttons: ['csv', 'excel', 'pdf', 'print', 'colvis']
                buttons: [ {
                   extend: 'pdf',
                   footer: false,
                   exportOptions: {
                   columns: [0,1, 2, 3, 4, 5, 6, 7,8,9]
                   }
                },
               //{
               //    extend: 'csv',
               //    footer: false

               //},
               {
                   extend: 'excel',
                   footer: false,
                   exportOptions: {
                   columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
                   }
               },
               
               {
                  extend: 'print',
                  footer: false,
                  exportOptions: {
                  columns: [0,1, 2, 3, 4, 5, 6, 7, 8, 9]
                  }
               },
               {
                   extend: 'colvis',
                   footer: false
               }
                    ]
            });
        });
   
            $(".anchorDetail").click(function () {
                //debugger;
                var $buttonClicked = $(this);

                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };

                $.ajax({
                    type: "GET",
                    url: '@Url.Action("Details", "ProjectInfoes")',
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        debugger;
                        $('#myModalContent').html(data);
                        $('#myModal').modal(options);
                        $('#myModal').modal('show');

                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
     

       
            $(".anchorEdit").click(function () {
                debugger;
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };

                $.ajax({
                    type: "GET",
                    url: '@Url.Action("Edit", "ProjectInfoes")',
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        debugger;
                        $('#myModalContent').html(data);
                        $('#myModal').modal(options);
                        $('#myModal').modal('show');

                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
       
    
        
            $(".anchorDelete").click(function () {
                debugger;
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };

                $.ajax({
                    type: "GET",
                    url: '@Url.Action("Delete", "ProjectInfoes")',
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        debugger;
                        $('#myModalContent').html(data);
                        $('#myModal').modal(options);
                        $('#myModal').modal('show');
                        $('#myModal').draggable();
                        //$('#myModal').toggle();
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
       
    </script>
}