CEGIS_Project_ProgressApp/Controllers/DivisionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CEGIS_Project_ProgressApp.Models;

namespace CEGIS_Project_ProgressApp.Controllers
{
    public class DivisionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Divisions
        public ActionResult Index()
        {
            return View(db.LookUpDivisions.ToList());
        }

        // GET: Divisions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LookUpDivision division = db.LookUpDivisions.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            return View(division);
        }

        // GET: Divisions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Divisions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DivisionId,ShortName,FullName")] LookUpDivision division)
        {
            if (ModelState.IsValid)
            {
                db.LookUpDivisions.Add(division);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(division);
        }

        // GET: Divisions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LookUpDivision division = db.LookUpDivisions.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            return View(division);
        }

        // POST: Divisions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DivisionId,ShortName,FullName")] LookUpDivision division)
        {
            if (ModelState.IsValid)
            {
                db.Entry(division).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(division);
        }

        // GET: Divisions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LookUpDivision division = db.LookUpDivisions.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            return View(division);
        }

        // POST: Divisions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LookUpDivision division = db.LookUpDivisions.Find(id);
            db.LookUpDivisions.Remove(division);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CEGIS_Project_ProgressApp/Controllers/ExpectedDatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CEGIS_Project_ProgressApp.Models;

namespace CEGIS_Project_ProgressApp.Controllers
{
    public class ExpectedDatesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ExpectedDates
        public ActionResult Index()
        {
            return View(db.ExpectedDates.ToList());
        }

        // GET: ExpectedDates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpectedDate expectedDate = db.ExpectedDates.Find(id);
            if (expectedDate == null)
            {
                return HttpNotFound();
            }
            return View(expectedDate);
        }

        // GET: ExpectedDates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExpectedDates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date")] ExpectedDate expectedDate)
        {
            if (ModelState.IsValid)
            {
                db.ExpectedDates.Add(expectedDate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(expectedDate);
        }

        // GET: ExpectedDates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpectedDate expectedDate = db.ExpectedDates.Find(id);
            if (expectedDate == null)
            {
                return HttpNotFound();
            }
            return View(expectedDate);
        }

        // POST: ExpectedDates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date")] ExpectedDate expectedDate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expectedDate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expectedDate);
        }

        // GET: ExpectedDates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpectedDate expectedDate = db.ExpectedDates.Find(id);
            if (expectedDate == null)
            {
                return HttpNotFound();
            }
            return View(expectedDate);
        }

        // POST: ExpectedDates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExpectedDate expectedDate = db.ExpectedDates.Find(id);
            db.ExpectedDates.Remove(expectedDate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CEGIS_Project_ProgressApp/Controllers/ProjectTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CEGIS_Project_ProgressApp.Models;

namespace CEGIS_Project_ProgressApp.Controllers
{
    public class ProjectTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProjectTypes
        public ActionResult Index()
        {
            return View(db.ProjectTypes.ToList());
        }

        // GET: ProjectTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectType projectType = db.ProjectTypes.Find(id);
            if (projectType == null)
            {
                return HttpNotFound();
            }
            return View(projectType);
        }

        // GET: ProjectTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TypeName,TypeFullName")] ProjectType projectType)
        {
            if (ModelState.IsValid)
            {
                db.ProjectTypes.Add(projectType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projectType);
        }

        // GET: ProjectTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectType projectType = db.ProjectTypes.Find(id);
            if (projectType == null)
            {
                return HttpNotFound();
            }
            return View(projectType);
        }

        // POST: ProjectTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TypeName,TypeFullName")] ProjectType projectType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projectType);
        }

        // GET: ProjectTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectType projectType = db.ProjectTypes.Find(id);
            if (projectType == null)
            {
                return HttpNotFound();
            }
            return View(projectType);
        }

        // POST: ProjectTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProjectType projectType = db.ProjectTypes.Find(id);
            db.ProjectTypes.Remove(projectType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CEGIS_Project_ProgressApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @{
        ViewBag.Color = "#254377";  //#254377  1.#0E5857
                                    //ViewBag.Image = "../images/background-images.jpg";
    }
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CEGIS Project Progress</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("style", required: false)
    <link href="~/Content/Site.css" rel="stylesheet" />
    @*if(User.Identity.Name=="SIH")*@


    <style>

        .footer_part {
            margin-top: 10px;
            text-align: center;
            background: @ViewBag.Color; /*#02393F*/
            padding: 10px;
            width: 100%;
            float: left;
        }

        input, select, textarea {
            max-width: 100% !important;
        }
        

    </style>
</head>
<body>
    @*<select id="Color">
            <option value="#254377">Red</option>
            <option value="#0E5857">Black</option>
        </select>*@

    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: @ViewBag.Color;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Project ProgressType", "Index", "ProjectInfoes", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    <li>
                        @*<a href="@Url.Action("Index", "Home", null, null, "~/images/CEGIS_logo.png")"/>*@
                        <img src="~/images/CEGIS_logo.png" style="height: 50px; padding: 5px" />

                    </li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>
                            @Html.ActionLink("Dashboard", "Index", "Home")
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown" style="padding: 10px">
                            <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown" style="background-color: @ViewBag.Color">
                                Admin Panel
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Add New User", "Register", "Account")</li>
                                <li>@Html.ActionLink("Add ProgressType", "Index", "ProgressTypes")</li>
                                <li>@Html.ActionLink("Add ProjectType", "Index", "ProjectTypes")</li>
                                <li>@Html.ActionLink("Add Division", "Index", "Divisions")</li>
                                <li>@Html.ActionLink("Add Expected Date", "Index", "ExpectedDates")</li>
                            </ul>
                        </li>
                    }                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>
    <h2 style="text-align: center; color: Black">Business Harnessing Monitoring Tools</h2>
    <hr />
    <div class="container body-content">
        <div class="loading">
            <div class="pageloading-body">
                <div class="loading-indicator">
                    @*<img src="http://sampsonresume.com/labs/pIkfp.gif" />*@
                    <p>Please wait</p>
                </div>
            </div>
        </div>
        <div id='myModal' class='modal'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div id='myModalContent'></div>
                </div>
            </div>

        </div>
        @RenderBody()
        <hr />
        <footer class="footer_part">
            <p style="color: white">Copyright @DateTime.Now.Year - All Rights Reserved By CEGIS</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/angular")*@
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('.loading').hide();
            //$("#Color").on('change', function () {

            //});
        });
    </script>
</body>
</html>